### ISSUE TITLE
[REQUEST] Build for GoLand 2024.2

### ISSUE THREAD

**Issue by brunoluizkatz-NETZSCH** [p0las/dividers#1]
Can be possible to build a new version release to GoLand 2024.2?

**Comment by brunoluizkatz-NETZSCH** [comment]
I add a PR to update to the new IDE version: https://github.com/p0las/dividers/pull/2

**Comment by ArthurMuniz-NETZSCH** [comment]
Seconded

**Comment by p0las** [comment]
of course. will tackle it tomorrow.

**Comment by p0las** [comment]
0.3.12 pending review. meantime zipped release is available on github.

**Comment by brunoluizkatz-NETZSCH** [comment]
Thanks a lot, I will close this issue.
